package com.example.pam_app.foodAndDrinks.model

import com.example.pam_app.R
import com.example.pam_app.foodAndDrinks.utils.Food

class ModelFood {
    private val foodList = ArrayList<Food>()
    fun prepareData(): ArrayList<Food> {
        var food = Food(R.drawable.carbonara, "Carbonara", "80 MDL")
        foodList.add(food)
        food = Food(R.drawable.lavnda_cake_69mdl, " Lavanda Cake", "69 MDL")
        foodList.add(food)
        food = Food(R.drawable.pizza_130mdl, "Pizza Set", "130 MDL")
        foodList.add(food)
        food = Food(R.drawable.happy_picnic_400mdl, "Happy Picnic", "400 MDL")
        foodList.add(food)
        food = Food(R.drawable.fresh_vegetables_150mdl, "Fresh Vegetables", "150 MDL")
        foodList.add(food)
        food = Food(R.drawable.grilled_vegetables_150mdl, "Grilled Vegetables", "150 MDL")
        foodList.add(food)
        food = Food(R.drawable.purcari_sauvignon_blank_156mdl, "Purcari Sauvignon Blank", "156 MDL")
        foodList.add(food)
        food = Food(R.drawable.oatmeal_with_fruits_43mdl, "Oatmeal with fruits", "43 MDL")
        foodList.add(food)
        food = Food(R.drawable.corn_soup_58mdl, "Corn Soup", "58 MDL")
        foodList.add(food)
        food = Food(R.drawable.meat_platter_300md, "Meat Platter", "300 MDL")
        foodList.add(food)
        food = Food(R.drawable.tuna_salad_70mdl, "Tuna Salad", "70 MDL")
        foodList.add(food)
        food = Food(R.drawable.fruit_plate, "Fruit Plate", "160 MDL")
        foodList.add(food)
        food = Food(R.drawable.ravioli_76mdll, "Ravioli", "76 MDL")
        foodList.add(food)
        food = Food(R.drawable.spinach_cream_soup_112mdl, "Spinach Cream-Soup", "112 MDL")
        foodList.add(food)
        food = Food(R.drawable.omelette_39mdl, "Omelette", "39 MDL")
        foodList.add(food)
        food = Food(R.drawable.homemade_red_whine_94, "Homemade red whine", "94 MDL")
        foodList.add(food)
        food = Food(R.drawable.fresh_51mdl, "Fresh", "51 MDL")
        foodList.add(food)
        food = Food(R.drawable.dorna_35mdl, "Dorna", "35 MDL")
        foodList.add(food)
        food = Food(R.drawable.tiramisu_57mdl, "Tiramisu", "57 MDL")
        foodList.add(food)
        food = Food(R.drawable.cheesecake_65mdl, "Cheesecake", "65 MDL")
        foodList.add(food)
        food = Food(R.drawable.fruid_salad_44mdl, "Fruit salad", "44 MDL")
        foodList.add(food)
        food = Food(R.drawable.ravioli_76mdll, "Ravioli", "76 MDL")
        foodList.add(food)
        food = Food(R.drawable.spinach_cream_soup_112mdl, "Spinach Cream-Soup", "112 MDL")
        foodList.add(food)
        food = Food(R.drawable.omelette_39mdl, "Omelette", "39 MDL")
        foodList.add(food)
        food = Food(R.drawable.homemade_red_whine_94, "Homemade red whine", "94 MDL")
        foodList.add(food)
        food = Food(R.drawable.fresh_51mdl, "Fresh", "51 MDL")
        foodList.add(food)
        food = Food(R.drawable.dorna_35mdl, "Dorna", "35 MDL")
        foodList.add(food)
        food = Food(R.drawable.corn_soup_58mdl, "Corn Soup", "58 MDL")
        foodList.add(food)
        food = Food(R.drawable.lavnda_cake_69mdl, " Lavanda Cake", "69 MDL")
        foodList.add(food)
        food = Food(R.drawable.pizza_130mdl, "Pizza Set", "130 MDL")
        foodList.add(food)
        food = Food(R.drawable.happy_picnic_400mdl, "Happy Picnic", "400 MDL")
        foodList.add(food)
        food = Food(R.drawable.fresh_vegetables_150mdl, "Fresh Vegetables", "150 MDL")
        foodList.add(food)
        food = Food(R.drawable.grilled_vegetables_150mdl, "Grilled Vegetables", "150 MDL")
        foodList.add(food)
        food = Food(R.drawable.purcari_sauvignon_blank_156mdl, "Purcari Sauvignon Blank", "156 MDL")
        foodList.add(food)
        food = Food(R.drawable.oatmeal_with_fruits_43mdl, "Oatmeal with fruits", "43 MDL")
        foodList.add(food)
        food = Food(R.drawable.corn_soup_58mdl, "Corn Soup", "58 MDL")
        foodList.add(food)
        return foodList
    }
}